language: cpp
compiler:
  - clang
  - gcc

# Install gcc 4.8 and cpp-coveralls
before_install:
  - sudo pip install cpp-coveralls
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

before_script:
  - source ./configure

script:
  - reconfigure -DENABLE_PROFILING=true && make
  - ./distance-projection/distance-projection