language: cpp
compiler:
  - clang
  - gcc

env:
  global:
    - secure: "NQ1OckGoSKZgkQGizyCNX1AMt1Yieeh5TTM/uVhHys9AqBjsOi2NiP+k0QJSqnVYxXm0jvde5vZsnoz+k9ey9x/0BTf+KKv3ldDo1S0iSKEz2UgK2H5KGTY4P7WDQ1u11H7xwv7hjHt09OrIGUVoA946DQZ2oX9lKFiWaPQHpbYxuEz3HSH1vJdB4oCXQCCk2kRM/ky49+t/X2yoiHKwLWYKzMZXCrAIBLvLrjY+ol47SnoiWoN5n8vrZFq9eNVihw8aFdBgUZZfmBGH8g+qgHl4Om+Ync3vd4J4utv9r1670bdOHVfwEmEu7GYli3j3fSqHLtSo4wCd4M5ZxsmBqhMomZkLuPWyoNuvk53jM0JPh6ry+Tg7nILLn/QWGjO4oVLi21ZBote4NX0o6dYlcJAlz08/cmzg+06eLFoosn7JPNhABl2+piuxoNvdRkbtQsBy3KKmmE3DyF5XNKYTst9MIiMwJhVHGn6t6fJdi3Q7gWmbc0pCkzW91mcUXso3kuR03JmWuc2tE9cF7ezBYmGD3rrZUx1DBcvnbJQRieiKGFvJtgsRR6ZQts9D5HFvgRjHp0CFzmyV5Qgy8kg0G2sWU7BdgGC2bpO/CsrhQwam0oPWauvLMdgzmW9D5ZHswp4obKWLvH31coSQHnYJS+3HTYCkPHpcoexmcVCKHfk="
  matrix:
    - CMAKE_ARGS="-DENABLE_PROFILING=t"

addons:
  coverity_scan:
    project:
      name: "r2labs/QuARC"
    notification_email: hershal.bhave@gmail.com
    build_command_prepend: "source ./configure; reconfigure"
    build_command:   "make -j4"
    branch_pattern: coverity_scan

# Install gcc 4.8 and cpp-coveralls
before_install:
  - sudo pip install cpp-coveralls
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

before_script:
  - source ./configure

script:
  - reconfigure ${CMAKE_ARGS} && make
  - ./distance-projection/distance-projection

after_success:
  - coveralls -b ${BUILD_ROOT} -r ${CMAKE_ROOT} -i ${CMAKE_ROOT} -e ${BUILD_ROOT}/CMakeFiles --gcov-options '\-lp'