language: cpp
compiler:
  - clang
  - gcc

env:
  - CMAKE_ARGS="-DPROFILE=1"

# Install gcc 4.8 and cpp-coveralls
before_install:
  - sudo pip install cpp-coveralls
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8 valgrind libboost-all-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 90

before_script:
  - source ./configure

script:
  - reconfigure ${CMAKE_ARGS} && make && make test

after_success:
  - coveralls -b ${BUILD_ROOT} -r ${CMAKE_ROOT} -e ${BUILD_ROOT}/CMakeFiles --gcov-options '\-lp'
