language: cpp
compiler:
  - clang
  - gcc

env:
  global:
    - secure: "YuHebcQDdQBNylCtg4pdu1VO2nEQvr4k/S6ZWyqg5FT7AnPgD2JzT1jqfO2xc4G7tH+NpxkJ4Tvn8b4T28QMZE72My1vT2Jnz689FUXz606I41yvxoeMrarq23I4Mwczr+jHneBMVKR9pgmfhssTrRT9vX5axBvFe72zbU8/dA2jWPX/nxilEoaKBoP2V0K8b/5JuvEsrUOGZf0t14I214ASO5zbws8K3uDqTW0wO4X0u8jcEKEOwFpHD9vdpWGK68pazME7THsEJGwJMgZswtSTvTdHpGliC3R0e0N1CeQZGClKtasxCJhXU7lvhfnvUBguCMauASD73tQ2nT0EObrvcj5wnqHnGwKXBjRUW8l1zRBnY+icKkXk3GbzsQYBI+NFoPcj0b+5qgZTVdHuYWpgmHHk1VVQ92pu+cmrckfgJ4mWAKFRpEzr88RR40f3ylkijE9iWAlSpMhIp+kTcI529iBNJv/Rqsj4NIDG36UIfEYZGvwmKI7XsNWexyiSjffw1VA/4noOy7z6x9FdXD20B/w2gM05eMNCWeqlfQ3cUwWqHMVjhOzCeKG/ciSGefTHShYyhD4mjXQ12min5EFD7RcgzfmXw0iFfbBUROMK/Fh44Q5VsfuXPoBr72BJL7X3XYgxCZM3Q0Tnc4jjMVMaKQo3pv3vEJltqZjK+fk="
  matrix:
    - CMAKE_ARGS="-DENABLE_PROFILING=t"

addons:
  coverity_scan:
    project:
      name: "r2labs/QuARC"
    notification_email: hershal.bhave@gmail.com
    build_command_prepend: "source ./configure; reconfigure"
    build_command:   "make -j4"
    branch_pattern: master

# Install gcc 4.8 and cpp-coveralls
before_install:
  - sudo pip install cpp-coveralls
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

before_script:
  - source ./configure

script:
  - reconfigure ${CMAKE_ARGS} && make
  - ./distance-projection/distance-projection

after_success:
  - coveralls -b ${BUILD_ROOT} -r ${CMAKE_ROOT} -i ${CMAKE_ROOT} -e ${BUILD_ROOT}/CMakeFiles --gcov-options '\-lp'